# G * 42 point coordinates in decimal (correct conversion from hex)
point_x = "7356913722468763155518092886238006860757299964193402191943647957243737021149"
point_y = "8353686781200727416994686754908207716480106082647483667993604622182232784267"
