# circuit_game_action Prover.toml
state_before_commitment = "0x20e49f82831a4e749aad30701dd1eaffd7b129d2df8c17605b71aa71d04c9cc"
state_after_commitment = "0x9f70d446ecce6fad41055f4c416c99dfdaebfec047902acca78acdb7b0e579b"
player_hash = "0x1f1f4774b72099f63283c0ea1c152439351f0fde6e296758d17810f72166211"

stack_p1_before = 86
stack_p2_before = 74
pot_before = 40
street_before = 2
current_player_before = 1
last_action_before = 4
last_bet_size_before = 20
street_bet_p1_before = 8
street_bet_p2_before = 20
status_before = 1
dealer = 1

action_type = 2
action_amount = 0

player1_hash = "0x1f1f4774b72099f63283c0ea1c152439351f0fde6e296758d17810f72166211"
player2_hash = "0xf10ecce07badc7b46c6c84552ea286581f0ad1fa3e6e0aaf8870bacb47cdb2b"
