# circuit_game_action Prover.toml
state_before_commitment = "0x293fde56c862d9a9ac11df53369b5a0cfcc2a385088452f86c2166d01879e83b"
state_after_commitment = "0x2de39b08a46da0ac06ec3a9a557e20a7e0413572a1a07f7207d148d77c0c4c3b"
player_hash = "0xf10ecce07badc7b46c6c84552ea286581f0ad1fa3e6e0aaf8870bacb47cdb2b"

stack_p1_before = 98
stack_p2_before = 98
pot_before = 4
street_before = 1
current_player_before = 2
last_action_before = 0
last_bet_size_before = 0
street_bet_p1_before = 0
street_bet_p2_before = 0
status_before = 1
dealer = 1

action_type = 5
action_amount = 0

player1_hash = "0x1f1f4774b72099f63283c0ea1c152439351f0fde6e296758d17810f72166211"
player2_hash = "0xf10ecce07badc7b46c6c84552ea286581f0ad1fa3e6e0aaf8870bacb47cdb2b"
