# circuit_game_action Prover.toml
state_before_commitment = "0x1a1cebcf7b39265016e4b93c49332a44dc2e62dd0e2d771cabd06264fcb8743a"
state_after_commitment = "0x2be0399d072796dd5238893765fd19777fd6c1d8560180d859fa32f2df2ac42f"
player_hash = "0x7a3e7ce5a92c43d0dc54395ee696edb9193a932a37af9dc89a78994c369574f"

stack_p1_before = 94
stack_p2_before = 98
pot_before = 8
street_before = 1
current_player_before = 2
last_action_before = 1
last_bet_size_before = 4
street_bet_p1_before = 4
street_bet_p2_before = 0
status_before = 1
dealer = 1

action_type = 2
action_amount = 0

player1_hash = "0x2f0e173c203d45fb935d3fc4f1f5b02c2c2a9a2259d0d819df8d7f88e4279fe0"
player2_hash = "0x7a3e7ce5a92c43d0dc54395ee696edb9193a932a37af9dc89a78994c369574f"
