# circuit_game_action Prover.toml
state_before_commitment = "0x2be0399d072796dd5238893765fd19777fd6c1d8560180d859fa32f2df2ac42f"
state_after_commitment = "0x125e47ef30280dbae9ec2bd5de576cc4f6b9dda118f00da9fd5d953887e9d8c4"
player_hash = "0x7a3e7ce5a92c43d0dc54395ee696edb9193a932a37af9dc89a78994c369574f"

stack_p1_before = 94
stack_p2_before = 94
pot_before = 12
street_before = 2
current_player_before = 2
last_action_before = 0
last_bet_size_before = 0
street_bet_p1_before = 0
street_bet_p2_before = 0
status_before = 1
dealer = 1

action_type = 5
action_amount = 0

player1_hash = "0x2f0e173c203d45fb935d3fc4f1f5b02c2c2a9a2259d0d819df8d7f88e4279fe0"
player2_hash = "0x7a3e7ce5a92c43d0dc54395ee696edb9193a932a37af9dc89a78994c369574f"
