# circuit_mask Prover.toml - Player 5 (5-player test)

input_card_commitment = "0xc8349eed65d5fbef2ec78b22706a1234aa00cd9981099bc8ee47487c6dd414d"
output_card_commitment = "0x15417782d1b3daf66d63e38b84ed7dba903ae7492eb9cf545e72bb90e95f0131"
player_pub_x = "0x1269852f00dc7c4c97fdc731cfd9f31142ebef7a1df89e5570591375b4c8732f"
player_pub_y = "0xecabbb5b8bed8eaa19692cedae15448c92de587253e2b700a4f70c0ec66cad"

input_epk_x = "0x23b00ee9c52a09861040fd1d53abc86eb9b86589de1c572485e6fa722967e951"
input_epk_y = "0x8959ab8008959374840ce2eba2ca75a32fca30c3043d386631f990d996b8523"
input_epk_is_inf = false
input_msg_x = "0x201cd4f4f520762180e74bf366932a166a7b16fc7989a65de4ad14e810d7bca3"
input_msg_y = "0x505ab4885148ae39b4788c9cfeaf9305b3c4fb42a311d9e9e97fdd7adc2f281"
input_pk_x = "0x3ff917f4707143d5c097f4309325be73292b5a42d39481285abd55a38f622aa"
input_pk_y = "0x2836dc65bab5d3e5268fda4f73262b82495569e7ce3956250d0c5e6947599955"
input_pk_is_inf = false

player_secret_lo = "0xf8c243c9c6050b7a69baeea734245e60"
player_secret_hi = "0x92f220da94b0d3e112171cb5e4df2f8"

nonce_lo = "0xe9cbcb9371774f3b190303901060a1c9"
nonce_hi = "0x2d86df85396f14b9f733b5db08fdce4"
