# circuit_mask Prover.toml - Player 1 (5-player test)

input_card_commitment = "0x43d9dd36df1e73ca909649640e4eec320cef066761b758014f2416dc1b12b5f"
output_card_commitment = "0x151dc9c08ff4a9e69ad17a8c1af677dccf3e845b8ca4d4b8a90e6f2d317f1124"
player_pub_x = "0x388f550c2d3fc73cbe7b187f4928834b848a2adb509f818d4aa19405491770"
player_pub_y = "0x222dfbf00e94a9ef81ec8e8d34f332915449c9695d3cc2091ec02ddd4bc3d498"

input_epk_x = "0x0"
input_epk_y = "0x0"
input_epk_is_inf = true
input_msg_x = "0xdada2e56f3defd5090cc1244898ff0327a76fac682db999a697bea613cb46e1"
input_msg_y = "0x1fefda613d574167dc4fcad6868902f96ee8ebb071200dd7ace09835773f802e"
input_pk_x = "0x0"
input_pk_y = "0x0"
input_pk_is_inf = true

player_secret_lo = "0xadc7af44bcdb4ea4f36d4af0a9d13661"
player_secret_hi = "0x2ac39daa67890ccbe418deceb4c14047"

nonce_lo = "0x675837c41c3dde1ee1d13f5e203902dc"
nonce_hi = "0x172df759aa44034b27a646b69fd8fed"
