# circuit_unmask Prover.toml - Player 4 (4-player test)

input_card_commitment = "0x2e0449c2ad225b62f7da17d8ae377d03ce686d003c834835c93aaa81334cc4fe"
output_card_commitment = "0x138010790ba584519b2086af6a0411fa67be92accab11737f69604e239355163"
player_pub_x = "0x5cf443be02beaec7538a413fd7b1d393ef079a657ea75728f9382c9bf991236"
player_pub_y = "0x2a0d5507eeec66132d811e3ad6f7d6bd04534ca13dcc2249191f3ae8d92657fc"

input_epk_x = "0x1520b52ed230f7a79062330e7bc8be0868cb1a9eb75d7e26fc88484fb1f78289"
input_epk_y = "0x2d086a826465e2a09812300a825f39200c397acc2274ad06615a089430376961"
input_msg_x = "0x1710b4dd7d10a0d54837ae4b439680e73ac403fdda2ad8ce7af8cfde20e6d0e4"
input_msg_y = "0xa3293b3484f97b5c9678600527b93aead03a93947ace8e7c7df043aa1457e56"
input_pk_x = "0x5cf443be02beaec7538a413fd7b1d393ef079a657ea75728f9382c9bf991236"
input_pk_y = "0x2a0d5507eeec66132d811e3ad6f7d6bd04534ca13dcc2249191f3ae8d92657fc"

player_secret_lo = "0x41dad89d74e63393a262957315ff0991"
player_secret_hi = "0x210aae0f4af427c4ae593249b7ad6ef0"
