# circuit_unmask Prover.toml - Player 3 (4-player test)

input_card_commitment = "0x2c7c021c525dc01cdfbb3755e2b0016de4b3a7424d11c54db7b148016b54ae1d"
output_card_commitment = "0x2e0449c2ad225b62f7da17d8ae377d03ce686d003c834835c93aaa81334cc4fe"
player_pub_x = "0x150df1ef958fb931e9a70c69b169386aeaa7ce78c9456cc8bb3a932403ea6113"
player_pub_y = "0xbc8f233a25d6a4629a2f9e626c5c534d7514f7b58c57ab260459a9cddb6138b"

input_epk_x = "0x1520b52ed230f7a79062330e7bc8be0868cb1a9eb75d7e26fc88484fb1f78289"
input_epk_y = "0x2d086a826465e2a09812300a825f39200c397acc2274ad06615a089430376961"
input_msg_x = "0x2e323946300aa383ee84d2950d5bc54bae9101c10ae5a9141c378ed933598591"
input_msg_y = "0x2ff059b0ad166ed347d2bd758991d76634a641ebca8b8fbb36dd887358532aad"
input_pk_x = "0x20997d09f3d4dd1b3b8f4fc639005189f4446177d640db857bf2e1a3ecf49f04"
input_pk_y = "0x2695273fe7097e8c716360710484886093460ec188bbb12cd42486bba7aaf624"

player_secret_lo = "0x1281b2d223a2c4bf9c6b4a30d7e2a19c"
player_secret_hi = "0x23940d08601ea1ddfab01729fbeaa183"
