# circuit_unmask Prover.toml - Player 1 (4-player test)

input_card_commitment = "0x264563b0053341d293349802e9275c1a66d42bb26ba39bfd394398aa39a69131"
output_card_commitment = "0x132cdd8054703bbee38e9beb3ee8f9bd672cf2288e9dd2c0f7d718217e25943e"
player_pub_x = "0x277ddf8155bbb253fae0327d7b026b921ec5bc11642727896827beebb912d86a"
player_pub_y = "0x13fb1e217e862fe13169bff2b766a6adc99f8881dac3820bbe339a342255b18c"

input_epk_x = "0x1520b52ed230f7a79062330e7bc8be0868cb1a9eb75d7e26fc88484fb1f78289"
input_epk_y = "0x2d086a826465e2a09812300a825f39200c397acc2274ad06615a089430376961"
input_msg_x = "0x1143fc7298cd95f9abe50297e85cbe0473c2563dc0182d0369c0aab2c7a51934"
input_msg_y = "0xd1f7a4d1b0010043a61ba8a0560cabf1802505b383c1d33eeaebf9d5a2382da"
input_pk_x = "0x30147b93f044e485104d390939b6b4e3e6f05790efda597084104dac3da93366"
input_pk_y = "0x12cd62c47818a146bbf9ec8ebc2be6d3f38e15c51275e46149d4c710af31692e"

player_secret_lo = "0xdf39befc83e5067c5c6facdaf63ea72f"
player_secret_hi = "0xdb24ac74a48d1517cebdfcfeb34bc70"
